# Generated by Django 4.1.5 on 2023-01-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('px_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('ru_name', models.CharField(max_length=255)),
                ('px_slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_negative', models.IntegerField()),
                ('feedback_positive', models.IntegerField()),
                ('predefined_amount', models.JSONField(blank=True)),
                ('fiat_amount_range_min', models.IntegerField()),
                ('fiat_amount_range_max', models.IntegerField()),
                ('fiat_price_per_btc', models.FloatField()),
                ('price_per_btc', models.FloatField()),
                ('fee_percentage', models.IntegerField()),
                ('payment_method_group_id', models.IntegerField()),
                ('percent_per_usd', models.FloatField()),
                ('require_full_name_visibility', models.BooleanField()),
                ('default_flow_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('px_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('ru_name', models.CharField(max_length=255)),
                ('px_slug', models.CharField(max_length=255)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='data.category')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('px_id', models.CharField(max_length=255)),
                ('verified', models.BooleanField()),
                ('sell_cur', models.CharField(choices=[('BTC', 'Bitcoin'), ('USDT', 'Tether')], max_length=128, verbose_name='cryptoCurrencyCode')),
                ('buy_cur', models.CharField(max_length=128, verbose_name='fiatCurrencyCode')),
                ('margin', models.FloatField()),
                ('payment_method_name', models.CharField(max_length=255)),
                ('payment_method_label', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('last_seen', models.CharField(max_length=255, verbose_name='lastSeenString')),
                ('average_trade_speed', models.CharField(max_length=255, verbose_name='releaseTimeMedianHumanize')),
                ('user_timezone', models.CharField(max_length=255)),
                ('offer_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], default='sell', max_length=128)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='data.category')),
                ('offer_detail', models.ForeignKey(db_column='offer_detail_id', on_delete=django.db.models.deletion.CASCADE, to='data.offerdetail')),
                ('tags', models.ManyToManyField(blank=True, related_name='offers', to='data.tag')),
            ],
        ),
    ]
