# Generated by Django 4.1.5 on 2023-01-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('native_language_code', models.CharField(max_length=2)),
                ('language_code', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('is_bot', models.BooleanField()),
            ],
        ),
    ]
