# Generated by Django 4.1.5 on 2023-01-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_tguser_is_admin_alter_tguser_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
