# Generated by Django 4.1.5 on 2023-01-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='faq_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='warranty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
