# Generated by Django 4.1.5 on 2023-01-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_offer_faq_link_offer_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='faq_link',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='faq',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='currency',
            field=models.ForeignKey(db_column='currency_ditail_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='data.currencydetail'),
        ),
    ]
