# Generated by Django 4.1.5 on 2023-01-16 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_currencydetail_remove_offer_faq_link_subcategory_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydetail',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.CreateModel(
            name='GiftOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Payment Received', 'peyment received'), ('Complete', 'complete')], max_length=128)),
                ('discount', models.FloatField()),
                ('amount', models.PositiveIntegerField()),
                ('offer', models.ForeignKey(db_column='offer_id', on_delete=django.db.models.deletion.CASCADE, to='data.offer')),
                ('user', models.ForeignKey(db_column='tg_user_id', on_delete=django.db.models.deletion.CASCADE, to='data.tguser')),
            ],
        ),
    ]
