# Generated by Django 4.1.5 on 2023-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_giftorder_created_at_alter_giftorder_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftorder',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
