# Generated by Django 4.1.5 on 2023-01-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_offer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='giftorder',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='giftorder',
            name='status',
            field=models.CharField(choices=[('Open', 'open'), ('Pending', 'pending'), ('Payment Received', 'payment received'), ('Complete', 'complete')], max_length=128),
        ),
        migrations.CreateModel(
            name='PaymentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510)),
                ('address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('method', models.ForeignKey(db_column='payment_method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.paymentmethod')),
            ],
        ),
    ]
