# Generated by Django 4.1.5 on 2023-01-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_paymentmethod_giftorder_price_tguser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='api_key_conf',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
