# Generated by Django 4.1.5 on 2023-01-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_paymentmethod_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftorder',
            name='callback_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
