# Generated by Django 4.1.5 on 2023-01-19 14:32

from django.db import migrations


def generate_id(apps, schema_editor):
    Order = apps.get_model('data', 'GiftOrder')
    orders = Order.objects.all()
    id = 1
    for order in orders:
        order.callback_id = id
        order.save()
        id += 1



class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_giftorder_callback_id'),
    ]

    operations = [
        migrations.RunPython(generate_id)
    ]
