# Generated by Django 4.1.5 on 2023-01-19 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20230119_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftorder',
            name='callback_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='giftorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
