# Generated by Django 4.1.5 on 2023-01-19 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_giftorder_callback_id_alter_giftorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
