# Generated by Django 4.1.5 on 2023-01-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_paymentmethod_secret_key_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydetail',
            name='type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('fiat', 'Fiat')], default='fiat', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.ForeignKey(db_column='currency_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.currencydetail')),
                ('order', models.ForeignKey(db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.giftorder')),
                ('tg_user', models.ForeignKey(db_column='tg_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.tguser')),
            ],
        ),
    ]
