# Generated by Django 4.1.5 on 2023-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_currencydetail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydetail',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
