# Generated by Django 4.1.5 on 2023-01-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_payment_txid_payment__type_payment_bc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(db_column='payment_address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.paymentaddress'),
        ),
    ]
