# Generated by Django 4.1.5 on 2023-01-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_payment_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
    ]
