# Generated by Django 4.1.5 on 2023-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_remove_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftorder',
            name='TxID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
