# Generated by Django 4.1.5 on 2023-01-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_giftorder_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaddress',
            name='network',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
