# Generated by Django 4.1.5 on 2023-01-23 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_alter_paymentaddress_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='giftorder',
            name='status',
            field=models.ForeignKey(db_column='payment_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.paymentstatus'),
        ),
    ]
