# Generated by Django 4.1.5 on 2023-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_paymentstatus_alter_giftorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name_plural': 'payment statuses'},
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
