# Generated by Django 4.1.5 on 2023-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_alter_paymentstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='ru_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
