# Generated by Django 4.1.5 on 2023-01-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_giftorder_payment_address_alter_paymentstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftorder',
            name='gift_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
