# Generated by Django 4.1.5 on 2023-01-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_giftorder_gift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='TxID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(blank=True, db_column='payment_address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.paymentaddress'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.giftorder'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tg_user',
            field=models.ForeignKey(blank=True, db_column='tg_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.tguser'),
        ),
    ]
