# Generated by Django 4.1.5 on 2023-01-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fiat_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
