# Generated by Django 4.1.5 on 2023-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_offer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
